version: '3'

services:

  consul:
    image: consul:1.6
    container_name: consul
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500

  service:
    image: node:10
    container_name: service
    restart: on-failure
    working_dir: /service
    command: bash -c "npm install && npm install nodemon -g && nodemon --exec npm start"
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - "./service:/service"
    environment:
      NODE_PORT: 3000
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      - consul
      - employee
      - role
      - department

  employee:
    image: node:10
    container_name: employee
    restart: on-failure
    working_dir: /service
    command: bash -c "npm install && npm install nodemon -g && nodemon --exec npm start"
    ports:
      - 3001:3000
      - 9230:9229
    volumes:
      - "./employee:/service"
    environment:
      NODE_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_NAME: employeeadmin
      DATABASE_USER: mysql
      DATABASE_PASSWORD: password
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_ID: employee
    depends_on:
      - consul
      - database

  role:
    image: node:10
    container_name: role
    restart: on-failure
    working_dir: /service
    command: bash -c "npm install && npm install nodemon -g && nodemon --exec npm start"
    ports:
      - 3002:3000
      - 9231:9229
    volumes:
      - "./role:/service"
    environment:
      NODE_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_NAME: employeeadmin
      DATABASE_USER: mysql
      DATABASE_PASSWORD: password
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_ID: role
    depends_on:
      - consul
      - database

  department:
    image: node:10
    container_name: department
    restart: on-failure
    working_dir: /service
    command: bash -c "npm install && npm install nodemon -g && nodemon --exec npm start"
    ports:
      - 3003:3000
      - 9232:9229
    volumes:
      - "./department:/service"
    environment:
      NODE_PORT: 3000
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_NAME: employeeadmin
      DATABASE_USER: mysql
      DATABASE_PASSWORD: password
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      CONSUL_ID: department
    depends_on:
      - consul
      - database

  database:
    image: mysql:5.7
    container_name: database
    restart: on-failure
    ports:
      - 6603:3306
    volumes:
      - ./assets/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      DATABASE_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employeeadmin
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password