services:

  employeeadmin:
    container_name: employeeadmin
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    volumes:
      - ./:/service
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - database

  database:
    container_name: mysql
    image: mysql:5.7
    env_file: .env
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
      - ./assets/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6603:3306"
    environment:
      DATABASE_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
