version: '3'

services:

  consul:
    image: consul:1.6.1
    container_name: consul
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500

  service:
    container_name: nginx
    build:
      context: service
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - consul
      - employee
      - role
      - department

  employee:
    container_name: employee
    build:
      context: employee
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    environment:
      CONSUL_ID: employee
    depends_on:
      - consul
      - database

  role:
    container_name: role
    build:
      context: role
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3002:3000
      - 9231:9229
    volumes:
      - "./role:/service"
    env_file: .env
    environment:
      CONSUL_ID: role
    depends_on:
      - consul
      - database

  department:
    container_name: department
    build:
      context: department
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    environment:
      CONSUL_ID: department
    depends_on:
      - consul
      - database

  database:
    image: mysql:5.7
    container_name: database
    restart: on-failure
    ports:
      - 6603:3306
    volumes:
      - ./assets/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      DATABASE_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: employeeadmin
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
